name: Call a reusable workflow and use its outputs

on:
  pull_request:
    branches:
      - master
jobs:
  job1:
    uses: cadu1982/workflow-b/.github/workflows/workflow-b.yml@master

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}

  job3:
    uses: cadu1982/hello-work/.github/workflows/workflow-reusable.yml@master

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - run: echo ${{ needs.job3.outputs.random-number }} 